# This is a basic workflow to help you get started with Actions

name: Build Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}         
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Convert postman collection to open api
        id: postman2openapi
        run: |
          FILE=open-api.yaml
          cargo install --git https://github.com/kevinswiber/postman2openapi --features binary
          postman2openapi GWS-DOCS.postman_collection.json > $FILE
          echo "printing the file..." $FILE
          echo "copying the file to archive directory"
          cp $FILE ./archive/open-api_`date +"%s"`.yaml
    
      - name: Commit the file
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
          fi

      - name: Save file to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
           