# This is a basic workflow to help you get started with Actions

name: RUST CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}          
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
      - run: |
          FILE=open-api.yaml
          cargo install --git https://github.com/kevinswiber/postman2openapi --features binary
          postman2openapi GWS-DOCS.postman_collection.json > $FILE
          echo "printing the file..." $FILE
    
      - name: Commit file
        id: commit
        run: |
          git config user.email "action@github.com"
          git config user.name "cresmet"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "add weather data"
            git remote rm origin
            git remote add origin https://cresmet:$PUSH_TOKEN@github.com/cresmet/new-postman-01.git
            git push origin HEAD:master
          else
            echo 'unable to detech changes'
          fi  